# Generated by Django 3.1 on 2020-09-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitor_code', models.BigIntegerField(blank=True, null=True)),
                ('competitor_name', models.TextField(blank=True, null=True)),
                ('competitor_surname', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'competitors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CreditStaging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.TextField(blank=True, null=True)),
                ('seller_region', models.TextField(blank=True, null=True)),
                ('seller_rayon', models.TextField(blank=True, null=True)),
                ('seller_edrpou', models.TextField(blank=True, null=True)),
                ('seller_ipn', models.TextField(blank=True, null=True)),
                ('seller_name', models.TextField(blank=True, null=True)),
                ('seller_state', models.TextField(blank=True, null=True)),
                ('buyer_region', models.TextField(blank=True, null=True)),
                ('buyer_rayon', models.TextField(blank=True, null=True)),
                ('buyer_edrpou', models.TextField(blank=True, null=True)),
                ('buyer_ipn', models.TextField(blank=True, null=True)),
                ('buyer_name', models.TextField(blank=True, null=True)),
                ('buyer_state', models.TextField(blank=True, null=True)),
                ('reestr_number', models.TextField(blank=True, null=True)),
                ('nn_number', models.TextField(blank=True, null=True)),
                ('ordering_date', models.DateField(blank=True, null=True)),
                ('registration_date', models.TextField(blank=True, null=True)),
                ('total_pay_cost', models.TextField(blank=True, null=True)),
                ('pdv_summ', models.TextField(blank=True, null=True)),
                ('number_20_percent_count', models.TextField(blank=True, db_column='20_percent_count', null=True)),
                ('number_7_percent_count', models.TextField(blank=True, db_column='7_percent_count', null=True)),
                ('rk_count', models.TextField(blank=True, null=True)),
                ('correction_cost', models.TextField(blank=True, null=True)),
                ('one_rk_cost', models.TextField(blank=True, null=True)),
                ('product_name', models.TextField(blank=True, null=True)),
                ('product_code', models.TextField(blank=True, null=True)),
                ('unit', models.TextField(blank=True, null=True)),
                ('count', models.TextField(blank=True, null=True)),
                ('one_product_cost', models.TextField(blank=True, null=True)),
                ('hash', models.BigIntegerField()),
            ],
            options={
                'db_table': 'credit_staging',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('eur_com', models.TextField(blank=True, db_column='EUR-COM', null=True)),
                ('eur_nbu', models.TextField(blank=True, db_column='EUR-NBU', null=True)),
                ('usd_com', models.TextField(blank=True, db_column='USD-COM', null=True)),
                ('usd_nbu', models.TextField(blank=True, db_column='USD-NBU', null=True)),
                ('eur_mb_buy', models.FloatField(blank=True, db_column='EUR-MB-BUY', null=True)),
                ('eur_mb_sale', models.FloatField(blank=True, db_column='EUR-MB-SALE', null=True)),
            ],
            options={
                'db_table': 'exchange',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Groupcodes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('gname', models.CharField(blank=True, max_length=255, null=True)),
                ('gcodes', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'groupcodes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GtdRecords',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_code', models.BigIntegerField(blank=True, null=True)),
                ('cost_fact', models.FloatField(blank=True, null=True)),
                ('cost_customs', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gtd_records',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NlCredit',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('doc_id', models.BigIntegerField(blank=True, null=True)),
                ('reestr_number', models.BigIntegerField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('one_product_cost', models.FloatField(blank=True, null=True)),
                ('count', models.FloatField(blank=True, null=True)),
                ('ordering_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nl_credit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NlOrg',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True, unique=True)),
                ('edrpou', models.BigIntegerField(unique=True)),
            ],
            options={
                'db_table': 'nl_org',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NlProduct',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nl_product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NlReestr',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('doc_id', models.BigIntegerField(blank=True, null=True)),
                ('reestr_number', models.BigIntegerField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('one_product_cost', models.FloatField(blank=True, null=True)),
                ('count', models.FloatField(blank=True, null=True)),
                ('ordering_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nl_reestr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=2000)),
                ('is_competitor', models.BooleanField()),
                ('edrpou', models.BigIntegerField(unique=True)),
            ],
            options={
                'db_table': 'organisation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('gtd_name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'records',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sender',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SenderTrademark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=255)),
                ('trademark', models.CharField(max_length=255)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sender_trademark',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TmAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.TextField(blank=True, null=True)),
                ('trademark', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tm_alias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TnvedGroup',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('gname', models.TextField(blank=True, null=True)),
                ('gcodes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tnved_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TnvedMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tnved_mark',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trademark',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'trademark',
                'managed': False,
            },
        ),
    ]
