# Generated by Django 3.1 on 2021-02-11 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0002_auto_20210211_1118'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='ArticlePages',
        ),
    ]
