# Generated by Django 3.1 on 2021-02-11 10:38

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0003_auto_20210211_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepages',
            name='Text',
            field=tinymce.models.HTMLField(),
        ),
    ]
