# Generated by Django 3.1 on 2021-02-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0004_auto_20210211_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepages',
            name='Text',
            field=models.TextField(max_length=65534),
        ),
    ]
