# Generated by Django 3.1 on 2021-02-21 13:21

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0005_auto_20210211_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepages',
            name='Text',
            field=tinymce.models.HTMLField(max_length=65534),
        ),
    ]
