# Generated by Django 3.1 on 2021-02-21 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0006_auto_20210221_1621'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticlePages',
            new_name='ArticlePage',
        ),
    ]
