# Generated by Django 3.1 on 2020-11-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='delimiter',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
