# Generated by Django 3.1 on 2020-11-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201123_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='lastlogin',
        ),
        migrations.AddField(
            model_name='profile',
            name='nal_part',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='ved_part',
            field=models.BooleanField(default=False),
        ),
    ]
