# Generated by Django 3.1 on 2020-11-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201125_2349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='profile',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'United States Dollar'), ('EUR', 'Euro'), ('UAH', 'Ukraine Hryvna')], max_length=30),
        ),
    ]
