# Generated by Django 3.1 on 2020-11-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201126_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD - Dollar'), ('EUR', 'EUR - Euro'), ('UAH', 'UAH - Hryvna')], max_length=30),
        ),
    ]
